spring.application.name=api

spring.datasource.url=JDBC:mysql://localhost/vollmed_api
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.username=root
spring.datasource.password=12345678

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.web.error.include-stacktrace=never

api.security.token.secret=${JWT_SECRET:12345678}