spring.application.name=api

spring.datasource.url=JDBC:mysql://localhost/vollmed_api
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.username=root
spring.datasource.password=12345678